# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac33aef826be3fff534a146a03245ad0d7ac85004219ce72c93877dafbbcd1bebfb2423ed5b684cc215be03c77a50a97d9372059d8d1d8d060e36f130172282

test:
  secret_key_base: 2c9a261835b681db11eb63c81aa414f2e038bd2511e7021ce592e4fdcc05b68da7e91fcf723fa5b0e246a5232b3ac4b05b89b8c9ed2ae20cce66c38f5016f693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
